#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="solids4Foam"

cp -r constant/polyMesh.orig constant/polyMesh
runApplication $application
