#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cp -r 0.orig 0


# Create the mesh
solids4Foam::runApplication blockMesh

# Run solver
if [[ "$1" == "parallel" ]]; then
    # Run parallel
    solids4Foam::runApplication decomposePar 
    solids4Foam::runParallel solids4Foam
    solids4Foam::runApplication reconstructPar 
else
    # Run serial
    solids4Foam::runApplication solids4Foam
fi