#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd "${0%/*}" || exit    

# Get application name
application="solids4Foam"

cp -r 0.orig 0
runApplication blockMesh
runApplication setFields
runApplication $application

sample -latestTime

python3 ./Plot.py