#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create meshes
solids4Foam::runApplication  blockMesh 

# Run solver
if [[ "$1" == "parallel" ]]; then
    # Run parallel
    solids4Foam::runApplication decomposePar 
    solids4Foam::runParallel dbnsDyMFoam
    solids4Foam::runApplication  reconstructPar 
else
    # Run serial
    solids4Foam::runApplication dbnsDyMFoam
fi

